### ISSUE TITLE
AWS LAMBDA FUNCTION HANDLER FOR RABBITMQ -- RABBITMQEVENT

### ISSUE THREAD

**Issue by aboah** [Kralizek/AWSLambdaSharpTemplate#20]
I would be grateful if shown the RabbitMQEvent class object( nugget package) that can be used to develop AWS Lambda Function.
Refer to AWS Lambda now supports Amazon MQ for RabbitMQ as an event source
Just as we have for Amazon.Lambda.S3Events
https://aws.amazon.com/about-aws/whats-new/2021/07/aws-lambda-now-supports-amazon-mq-for-rabbitmq-as-an-event-source/

**Comment by Kralizek** [comment]
In the documentation article linked below, you can find a sample of the message sent to the lambda function. Simply create a C# class that matches the record and you should be good to go.

https://docs.aws.amazon.com/lambda/latest/dg/with-mq.html

I'll close it for now, please reopen if you have more questions.
